#!/usr/bin/env python3
"""Generate ca_bundle.h from cacert.pem.

Embeds the Mozilla CA bundle (pinned at fetch time) as a C uint8_t array so
the _ssl_capability extension can `load_default_certs()` without filesystem
access. Re-run this when bumping the bundle:

    curl -sSfL https://curl.se/ca/cacert.pem -o cpython-ext/_ssl/ca-bundle/cacert.pem
    python3 cpython-ext/_ssl/ca-bundle/embed-ca-bundle.py

Output: cpython-ext/_ssl/ca-bundle/ca_bundle.h (committed).
"""

import hashlib
import sys
from pathlib import Path

HERE = Path(__file__).parent
PEM = HERE / "cacert.pem"
OUT = HERE / "ca_bundle.h"

data = PEM.read_bytes()
digest = hashlib.sha256(data).hexdigest()

# Try to extract the bundle date from the file's own header (Mozilla format).
date = "unknown"
for line in data.decode("utf-8", "replace").splitlines()[:20]:
    if "Certificate data from Mozilla as of:" in line:
        date = line.split(":", 1)[1].strip()
        break
cert_count = data.count(b"BEGIN CERTIFICATE")

bytes_per_line = 16
hex_rows = []
for i in range(0, len(data), bytes_per_line):
    chunk = data[i : i + bytes_per_line]
    hex_rows.append("  " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")

with OUT.open("w") as f:
    f.write(f"""/* AUTO-GENERATED by cpython-ext/_ssl/ca-bundle/embed-ca-bundle.py
 *   DO NOT EDIT BY HAND.
 *
 * Source: cpython-ext/_ssl/ca-bundle/cacert.pem
 * SHA-256: {digest}
 * Mozilla bundle date: {date}
 * Certificate count: {cert_count}
 * Size: {len(data)} bytes
 */

#ifndef SSL_CAPABILITY_CA_BUNDLE_H
#define SSL_CAPABILITY_CA_BUNDLE_H

#include <stddef.h>
#include <stdint.h>

static const uint8_t SSL_CAPABILITY_CA_BUNDLE_PEM[] = {{
{chr(10).join(hex_rows)}
}};

#define SSL_CAPABILITY_CA_BUNDLE_PEM_LEN ((size_t) {len(data)})
#define SSL_CAPABILITY_CA_BUNDLE_SHA256 "{digest}"
#define SSL_CAPABILITY_CA_BUNDLE_DATE "{date}"
#define SSL_CAPABILITY_CA_BUNDLE_CERT_COUNT {cert_count}

#endif
""")
print(f"wrote {OUT} ({len(data)} bytes, {cert_count} certs, sha256={digest[:16]}...)")
