#!/usr/bin/env bash
# Wire every cpython-ext/_<name>/ capability extension into the CPython
# wasi-sdk build so the next `make build` will statically link them.
#
# Two things have to be true for a capability extension to be picked up by
# Tools/wasm/wasi build:
#
#   1. There's a symlink at $CPYTHON_DIR/Modules/<modname> pointing back at
#      this repo's cpython-ext/<srcdir>/. (Tools/wasm/wasi walks Modules/.)
#   2. There's a line for it in $CPYTHON_DIR/Modules/Setup.local of the form
#         <modname> <modname>/<modulefile.c> \
#                   <modname>/gen/<import>.c \
#                   <absolute>/cpython-ext/<srcdir>/gen/<import>_component_type.o \
#                   -I$(srcdir)/Modules/<modname>/gen
#      with the .o path absolute because Tools/wasm/wasi resolves -I against
#      the per-host cross-build dir but not extra-object-file paths.
#
# Neither is checked into either git (deps/cpython is gitignored), so this
# script regenerates both, idempotently, every time it's run. Hand-editing
# Setup.local works too; this script just keeps a clean source of truth.
#
# Adding a new extension is then: drop the directory in cpython-ext/,
# follow the file-name convention (or add an explicit case below for any
# special-case mapping like _ssl -> _ssl_capability), re-run this script.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

PROFILE="${PROFILE:-default}"
eval "$(bash "$SCRIPT_DIR/load-profile.sh" "$PROFILE")"

CPYTHON_DIR="$PROJECT_DIR/deps/$PYTHON_SOURCE_DIR"

if [ ! -d "$CPYTHON_DIR/Modules" ]; then
    echo "wire-cpython-ext: $CPYTHON_DIR/Modules missing — run \`make fetch-deps\` first." >&2
    exit 1
fi

EXT_DIR="$PROJECT_DIR/cpython-ext"

# Phase 8: pyforge-pkg.toml is the single source of truth for each
# extension's identity (srcdir, module_name, c_file, gen_import_c,
# gen_import_obj). Glob cpython-ext/*/pyforge-pkg.toml and parse the
# [extension] section. Shim-only directories (no [extension] block,
# pattern = "shim-only") are filtered out — they're install-python-
# shims-side, not Modules/Setup.local-side.
#
# Use python3's tomllib because it's already required elsewhere in
# the build. Filter via OFFLOAD_PKGS_INCLUDE / OFFLOAD_PKGS_EXCLUDE
# from the env so subset builds (e.g. scripts/build-from-pkgs.sh)
# can opt in/out of specific packages.
EXTS_FILE="$(mktemp)"
trap 'rm -f "$EXTS_FILE"' EXIT

python3 - "$EXT_DIR" "${PYFORGE_PKGS_INCLUDE:-}" "${PYFORGE_PKGS_EXCLUDE:-}" > "$EXTS_FILE" <<'PYEOF'
import os
import pathlib
import sys
import tomllib

ext_dir = pathlib.Path(sys.argv[1])
include = {n for n in sys.argv[2].split(",") if n}
exclude = {n for n in sys.argv[3].split(",") if n}

for manifest in sorted(ext_dir.glob("*/pyforge-pkg.toml")):
    with open(manifest, "rb") as fh:
        pkg = tomllib.load(fh)
    name = pkg.get("package", {}).get("name", manifest.parent.name)
    if include and name not in include:
        continue
    if exclude and name in exclude:
        continue
    ext = pkg.get("extension")
    if not ext:
        continue                     # shim-only — no Setup.local entry
    print("|".join([
        ext["srcdir"],
        ext["module_name"],
        ext["c_file"],
        ext["gen_import_c"],
        ext["gen_import_obj"],
    ]))
PYEOF

declare -a EXTS=()
while IFS= read -r line; do
    [ -n "$line" ] && EXTS+=("$line")
done < "$EXTS_FILE"

# Per-variant gating that the pyforge schema doesn't yet model:
# WITH_V86_POSIX=0 (browser builds) drops _v86_posix from the build.
if [ "${WITH_V86_POSIX:-1}" != "1" ]; then
    NEW_EXTS=()
    for entry in "${EXTS[@]}"; do
        case "$entry" in
            _v86_posix\|*) ;;        # skip
            *) NEW_EXTS+=("$entry") ;;
        esac
    done
    EXTS=("${NEW_EXTS[@]}")
fi

SETUP_LOCAL="$CPYTHON_DIR/Modules/Setup.local"
TMP_SETUP="$(mktemp)"
trap 'rm -f "$TMP_SETUP"' EXIT

# Header matches what `python3 Tools/wasm/wasi build` writes when it first
# initialises Setup.local for a clean tree.
#
# *disabled* zlib: Tier A retires the static `_zlib` C extension (and its
# `-lz` link dep) in favor of `Lib/zlib.py` shim → `_compress_cap.deflate_*`.
# CPython's built-in module loader prefers static extensions over .py files,
# so we MUST disable the C extension here for the shim to be picked up by
# `import zlib`. The trailing `*static*` directive switches the parser back
# to "define static modules" mode so the lines below define extensions
# (not disable them).
cat > "$TMP_SETUP" <<'EOF'
# Generated by Tools/wasm/wasi .
# Required to statically build extension modules.

*disabled*
zlib
EOF

# Phase 3 of docs/coverage-implementation-plan.md: in production builds,
# disable the in-tree test C extensions. They live in python.wasm purely
# to support CPython's own test suite; nothing python-wasm ships actually
# uses them. After strip they're still ~1 MiB of compiled wasm bytes.
# Opt out (e.g. for test-suite work) with DROP_TEST_C_EXTS=0.
if [ "${DROP_TEST_C_EXTS:-1}" = "1" ]; then
    cat >> "$TMP_SETUP" <<'EOF'
_testbuffer
_testcapi
_testclinic
_testclinic_limited
_testinternalcapi
_testlimitedcapi
_xxtestfuzz
xxsubtype
EOF
fi

cat >> "$TMP_SETUP" <<'EOF'

*static*
EOF

# Clean stale per-variant artifacts when their flag is off. If a previous
# build wired _v86_posix and the user now sets WITH_V86_POSIX=0, the
# Modules/_v86_posix symlink + the cross-build/.../Modules/_v86_posix
# object tree would otherwise re-link the old .o into the new bare
# python.wasm — silently producing the wrong artifact.
if [ "${WITH_V86_POSIX:-1}" != "1" ]; then
    rm -f "$CPYTHON_DIR/Modules/_v86_posix"
    for cross_dir in "$CPYTHON_DIR"/cross-build/wasm*/Modules; do
        rm -rf "$cross_dir/_v86_posix"
    done
fi

echo "wire-cpython-ext: wiring $(echo "${EXTS[@]}" | wc -w | tr -d ' ') extensions into $CPYTHON_DIR/Modules/"

for entry in "${EXTS[@]}"; do
    IFS='|' read -r srcdir modname cfile genc genobj <<< "$entry"

    ext_path="$EXT_DIR/$srcdir"
    if [ ! -d "$ext_path" ]; then
        echo "  ! cpython-ext/$srcdir/ missing — skipping" >&2
        continue
    fi
    if [ ! -f "$ext_path/$cfile" ]; then
        echo "  ! cpython-ext/$srcdir/$cfile missing — skipping" >&2
        continue
    fi
    if [ ! -f "$ext_path/gen/$genc" ] || [ ! -f "$ext_path/gen/$genobj" ]; then
        echo "  ! cpython-ext/$srcdir/gen/{$genc,$genobj} missing — run wit-bindgen, then re-run this script" >&2
        continue
    fi

    # (Re-)point the symlink at the source dir. -h makes -f cope with an
    # existing symlink atomically; replace_all on ln isn't a thing.
    ln -sfn "$ext_path" "$CPYTHON_DIR/Modules/$modname"
    echo "  + symlink: Modules/$modname -> cpython-ext/$srcdir"

    # Pre-create the build-tree output dirs for each wasm cross-build that
    # exists. Tools/wasm/wasi build doesn't mkdir these on demand; on a
    # fresh extension the first build aborts with:
    #   unable to open output file 'Modules/<modname>/gen/<x>.o': No such file or directory
    # Doing it here is idempotent and a one-liner per cross-build.
    for cross_dir in "$CPYTHON_DIR"/cross-build/wasm*/Modules; do
        [ -d "$cross_dir" ] && mkdir -p "$cross_dir/$modname/gen"
    done

    # Append the Setup.local line.
    printf '%s %s/%s %s/gen/%s %s/gen/%s -I$(srcdir)/Modules/%s/gen\n' \
        "$modname" \
        "$modname" "$cfile" \
        "$modname" "$genc" \
        "$ext_path" "$genobj" \
        "$modname" \
        >> "$TMP_SETUP"
done

# Tools/wasm/wasi build's configure step copies Modules/Setup.local into
# each cross-build dir (e.g. cross-build/wasm32-wasip2/Modules/Setup.local)
# and the actual make uses *that* copy, not the top-level one. So we have to
# update every location that matters: the top-level (for fresh configures)
# AND the wasm32-wasip2 cross-build (for in-place rebuilds). We must NOT
# touch the host bootstrap python's cross-build (typically aarch64-apple-…
# or x86_64-unknown-linux-…) — those builds compile native binaries that
# can't link against the wasm capability extensions.
declare -a TARGETS=("$SETUP_LOCAL")
for cross_dir in "$CPYTHON_DIR"/cross-build/wasm*/Modules; do
    [ -d "$cross_dir" ] && TARGETS+=("$cross_dir/Setup.local")
done

for tgt in "${TARGETS[@]}"; do
    if [ ! -f "$tgt" ] || ! cmp -s "$TMP_SETUP" "$tgt"; then
        cp "$TMP_SETUP" "$tgt"
        echo "  + wrote $tgt"
    else
        echo "  = $tgt already current"
    fi
done

echo "wire-cpython-ext: done. Run \`make build\` to (re-)build python.wasm with the wired extensions."
