#!/usr/bin/env bash
# Wire every cpython-ext/_<name>/ capability extension into the CPython
# wasi-sdk build so the next `make build` will statically link them.
#
# Two things have to be true for a capability extension to be picked up by
# Tools/wasm/wasi build:
#
#   1. There's a symlink at $CPYTHON_DIR/Modules/<modname> pointing back at
#      this repo's cpython-ext/<srcdir>/. (Tools/wasm/wasi walks Modules/.)
#   2. There's a line for it in $CPYTHON_DIR/Modules/Setup.local of the form
#         <modname> <modname>/<modulefile.c> \
#                   <modname>/gen/<import>.c \
#                   <absolute>/cpython-ext/<srcdir>/gen/<import>_component_type.o \
#                   -I$(srcdir)/Modules/<modname>/gen
#      with the .o path absolute because Tools/wasm/wasi resolves -I against
#      the per-host cross-build dir but not extra-object-file paths.
#
# Neither is checked into either git (deps/cpython is gitignored), so this
# script regenerates both, idempotently, every time it's run. Hand-editing
# Setup.local works too; this script just keeps a clean source of truth.
#
# Adding a new extension is then: drop the directory in cpython-ext/,
# follow the file-name convention (or add an explicit case below for any
# special-case mapping like _ssl -> _ssl_capability), re-run this script.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

PROFILE="${PROFILE:-default}"
eval "$(bash "$SCRIPT_DIR/load-profile.sh" "$PROFILE")"

CPYTHON_DIR="$PROJECT_DIR/deps/$PYTHON_SOURCE_DIR"

if [ ! -d "$CPYTHON_DIR/Modules" ]; then
    echo "wire-cpython-ext: $CPYTHON_DIR/Modules missing — run \`make fetch-deps\` first." >&2
    exit 1
fi

EXT_DIR="$PROJECT_DIR/cpython-ext"

# Resolve each cpython-ext/<srcdir>/ to its (module_name, srcdir, c_file,
# gen_import_c, gen_import_obj). Conventional case = all five derive from
# srcdir; the special-case table below handles the historical _ssl mapping.
#
# Format: srcdir|module_name|c_file|gen_import_c|gen_import_obj
# Capability extensions always wired in. Per-variant ones are appended
# below based on env-var flags.
declare -a EXTS=(
    "_compression|_compress_cap|_compressionmodule.c|compression_import.c|compression_import_component_type.o"
    "_zlib_cap|_zlib_cap|_zlib_capmodule.c|zlib_cap_import.c|zlib_cap_import_component_type.o"
    "_bz2_cap|_bz2_cap|_bz2_capmodule.c|bz2_cap_import.c|bz2_cap_import_component_type.o"
    "_lzma_cap|_lzma_cap|_lzma_capmodule.c|lzma_cap_import.c|lzma_cap_import_component_type.o"
    "_zstd_cap|_zstd_cap|_zstd_capmodule.c|zstd_cap_import.c|zstd_cap_import_component_type.o"
    "_crypto_hash|_crypto_hash|_crypto_hashmodule.c|crypto_hash_import.c|crypto_hash_import_component_type.o"
    "_xxhash|_xxhash|_xxhashmodule.c|xxhash_import.c|xxhash_import_component_type.o"
    "_ssl|_ssl_capability|_ssl_capability_module.c|ssl_import.c|ssl_import_component_type.o"
    "_sqlite_capability|_sqlite_cap|_sqlite_capability_module.c|sqlite_import.c|sqlite_import_component_type.o"
    "_kdf_cap|_kdf_cap|_kdf_capmodule.c|kdf_cap_import.c|kdf_cap_import_component_type.o"
)

# pylon Phase 4.1 variant: _v86_posix is omitted from the browser
# build (WITH_V86_POSIX=0). Default ON preserves the existing v86-
# composed shape used by every current build script + test. See
# pylon-pyforge-implementation.md §4.1.
if [ "${WITH_V86_POSIX:-1}" = "1" ]; then
    # The v86:posix/process import is plugged in by
    # compose-python-component.sh via V86_POSIX_COMPONENT (default:
    # v86-posix-stub — every spawn returns guest-not-ready until v86-
    # component proper grows the real impl).
    EXTS+=("_v86_posix|_v86_posix|_v86_posixmodule.c|v86_posix_import.c|v86_posix_import_component_type.o")
fi

SETUP_LOCAL="$CPYTHON_DIR/Modules/Setup.local"
TMP_SETUP="$(mktemp)"
trap 'rm -f "$TMP_SETUP"' EXIT

# Header matches what `python3 Tools/wasm/wasi build` writes when it first
# initialises Setup.local for a clean tree.
#
# *disabled* zlib: Tier A retires the static `_zlib` C extension (and its
# `-lz` link dep) in favor of `Lib/zlib.py` shim → `_compress_cap.deflate_*`.
# CPython's built-in module loader prefers static extensions over .py files,
# so we MUST disable the C extension here for the shim to be picked up by
# `import zlib`. The trailing `*static*` directive switches the parser back
# to "define static modules" mode so the lines below define extensions
# (not disable them).
cat > "$TMP_SETUP" <<'EOF'
# Generated by Tools/wasm/wasi .
# Required to statically build extension modules.

*disabled*
zlib

*static*
EOF

# Clean stale per-variant artifacts when their flag is off. If a previous
# build wired _v86_posix and the user now sets WITH_V86_POSIX=0, the
# Modules/_v86_posix symlink + the cross-build/.../Modules/_v86_posix
# object tree would otherwise re-link the old .o into the new bare
# python.wasm — silently producing the wrong artifact.
if [ "${WITH_V86_POSIX:-1}" != "1" ]; then
    rm -f "$CPYTHON_DIR/Modules/_v86_posix"
    for cross_dir in "$CPYTHON_DIR"/cross-build/wasm*/Modules; do
        rm -rf "$cross_dir/_v86_posix"
    done
fi

echo "wire-cpython-ext: wiring $(echo "${EXTS[@]}" | wc -w | tr -d ' ') extensions into $CPYTHON_DIR/Modules/"

for entry in "${EXTS[@]}"; do
    IFS='|' read -r srcdir modname cfile genc genobj <<< "$entry"

    ext_path="$EXT_DIR/$srcdir"
    if [ ! -d "$ext_path" ]; then
        echo "  ! cpython-ext/$srcdir/ missing — skipping" >&2
        continue
    fi
    if [ ! -f "$ext_path/$cfile" ]; then
        echo "  ! cpython-ext/$srcdir/$cfile missing — skipping" >&2
        continue
    fi
    if [ ! -f "$ext_path/gen/$genc" ] || [ ! -f "$ext_path/gen/$genobj" ]; then
        echo "  ! cpython-ext/$srcdir/gen/{$genc,$genobj} missing — run wit-bindgen, then re-run this script" >&2
        continue
    fi

    # (Re-)point the symlink at the source dir. -h makes -f cope with an
    # existing symlink atomically; replace_all on ln isn't a thing.
    ln -sfn "$ext_path" "$CPYTHON_DIR/Modules/$modname"
    echo "  + symlink: Modules/$modname -> cpython-ext/$srcdir"

    # Pre-create the build-tree output dirs for each wasm cross-build that
    # exists. Tools/wasm/wasi build doesn't mkdir these on demand; on a
    # fresh extension the first build aborts with:
    #   unable to open output file 'Modules/<modname>/gen/<x>.o': No such file or directory
    # Doing it here is idempotent and a one-liner per cross-build.
    for cross_dir in "$CPYTHON_DIR"/cross-build/wasm*/Modules; do
        [ -d "$cross_dir" ] && mkdir -p "$cross_dir/$modname/gen"
    done

    # Append the Setup.local line.
    printf '%s %s/%s %s/gen/%s %s/gen/%s -I$(srcdir)/Modules/%s/gen\n' \
        "$modname" \
        "$modname" "$cfile" \
        "$modname" "$genc" \
        "$ext_path" "$genobj" \
        "$modname" \
        >> "$TMP_SETUP"
done

# Tools/wasm/wasi build's configure step copies Modules/Setup.local into
# each cross-build dir (e.g. cross-build/wasm32-wasip2/Modules/Setup.local)
# and the actual make uses *that* copy, not the top-level one. So we have to
# update every location that matters: the top-level (for fresh configures)
# AND the wasm32-wasip2 cross-build (for in-place rebuilds). We must NOT
# touch the host bootstrap python's cross-build (typically aarch64-apple-…
# or x86_64-unknown-linux-…) — those builds compile native binaries that
# can't link against the wasm capability extensions.
declare -a TARGETS=("$SETUP_LOCAL")
for cross_dir in "$CPYTHON_DIR"/cross-build/wasm*/Modules; do
    [ -d "$cross_dir" ] && TARGETS+=("$cross_dir/Setup.local")
done

for tgt in "${TARGETS[@]}"; do
    if [ ! -f "$tgt" ] || ! cmp -s "$TMP_SETUP" "$tgt"; then
        cp "$TMP_SETUP" "$tgt"
        echo "  + wrote $tgt"
    else
        echo "  = $tgt already current"
    fi
done

echo "wire-cpython-ext: done. Run \`make build\` to (re-)build python.wasm with the wired extensions."
